from django.urls import path
from . import views
from .views import upload_note_file, delete_note_file, update_note_order_and_notes, get_file_preview_url, get_file_preview_url_note

urlpatterns = [
    path('', views.diary_list, name='diary_list'),
    path('fu_events/', views.fu_events, name='fu_events'),
    path('fu_memo/<int:entry_id>/', views.fu_memo, name='fu_memo'),
    path('categories/', views.category_list, name='category_list'),
    path('regions/', views.region_list, name='region_list'),
    path('create/', views.create_entry, name='create_entry'),
    path('reorder/', views.reorder_entries, name='reorder_entries'),
    path('statuses/', views.status_list, name='status_list'),
    path('board/', views.board_view, name='board_view'),
    path('update/', views.update_entry, name='update_entry'),
    path('create_new_row/', views.create_new_row, name='create_new_row'),
    path('update_row_field/', views.update_row_field, name='update_row_field'),
    path('update_sales_field/', views.update_sales_field, name='update_sales_field'),
    path('dropdown_options/', views.dropdown_options, name='dropdown_options'),
    path('add_attribute/', views.add_attribute, name='add_attribute'),
    path('delete_attribute/', views.delete_attribute, name='delete_attribute'),
    path('get_row_details/<int:row_id>/', views.get_row_details, name='get_row_details'),
    path('debug_fu_data/', views.debug_fu_data, name='debug_fu_data'),
    path('get_user_attributes/', views.get_user_attributes, name='get_user_attributes'),
    path('get_kanban_data/', views.get_kanban_data, name='get_kanban_data'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('download_file/<int:row_id>/<str:field_name>/', views.download_file, name='download_file'),
    path('delete_file/', views.delete_file, name='delete_file'),
    path('upload_audio_file/', views.upload_audio_file, name='upload_audio_file'),
    path('get_audio_files_by_date/', views.get_audio_files_by_date, name='get_audio_files_by_date'),
    path('delete_audio_file/', views.delete_audio_file, name='delete_audio_file'),
    path('update_audio_text/', views.update_audio_text, name='update_audio_text'),
    path('update_audio_memo/', views.update_audio_memo, name='update_audio_memo'),
    path('update_audio_file_order/', views.update_audio_file_order, name='update_audio_file_order'),
    path('update_expected_loans/', views.update_expected_loans, name='update_expected_loans'),
    path('update_loan_amount/', views.update_loan_amount, name='update_loan_amount'),
    path('update_debt_field/', views.update_debt_field, name='update_debt_field'),
    path('get_debt_details/<int:row_id>/', views.get_debt_details, name='get_debt_details'),
    path('save_debt_details/', views.save_debt_details, name='save_debt_details'),
    path('get_funding_recommendation/', views.get_funding_recommendation, name='get_funding_recommendation'),
    path('get_recommended_notices/', views.get_recommended_notices, name='get_recommended_notices'),
    path('save_column_order/', views.save_column_order, name='save_column_order'),
    path('delete_row/', views.delete_row, name='delete_row'),
    path('duplicate_row/', views.duplicate_row, name='duplicate_row'),
    path('update_audio_text_notes/', views.update_audio_text_notes, name='update_audio_text_notes'),
    path('update_audio_file_order_and_notes/', views.update_audio_file_order_and_notes, name='update_audio_file_order_and_notes'),
    path('entry_table_partial/', views.entry_table_partial, name='entry_table_partial'),
    path('toggle_attribute_visibility/', views.toggle_attribute_visibility, name='toggle_attribute_visibility'),
    path('get_hidden_attributes/', views.get_hidden_attributes, name='get_hidden_attributes'),
    path('get_all_attributes/', views.get_all_attributes, name='get_all_attributes'),
    path('get_dropdown_attributes/', views.get_dropdown_attributes, name='get_dropdown_attributes'),
    path('update_attribute_name/', views.update_attribute_name, name='update_attribute_name'),
    path('get_status_tabs/', views.get_status_tabs, name='get_status_tabs'),
    path('upload_note_file/', upload_note_file, name='upload_note_file'),
    path('delete_note_file/', delete_note_file, name='delete_note_file'),
    path('update_note_order_and_notes/', update_note_order_and_notes, name='update_note_order_and_notes'),
    path('get_file_preview_url/<str:row_id>/<str:field_name>/', get_file_preview_url, name='get_file_preview_url'),
    path('get_file_preview_url_note/<str:file_id>/', get_file_preview_url_note, name='get_file_preview_url_note'),
    
    # 캘린더 설정 관련 API
    path('get_datetime_attributes/', views.get_datetime_attributes, name='get_datetime_attributes'),
    path('get_calendar_settings/', views.get_calendar_settings, name='get_calendar_settings'),
    path('save_calendar_settings/', views.save_calendar_settings, name='save_calendar_settings'),
    path('calendar_events/', views.calendar_events, name='calendar_events'),
    
    # Cascade 관련 API
    path('toggle_cascade_attribute/', views.toggle_cascade_attribute, name='toggle_cascade_attribute'),
    path('get_cascade_attributes_list/', views.get_cascade_attributes_list, name='get_cascade_attributes_list'),
    
    # 디버깅용 API
    path('fix_existing_row_relationships/', views.fix_existing_row_relationships, name='fix_existing_row_relationships'),
    path('debug_row_relationships/', views.debug_row_relationships, name='debug_row_relationships'),
    path('setup_test_cascade_attributes/', views.setup_test_cascade_attributes, name='setup_test_cascade_attributes'),
] 