# Generated by Django 5.0.2 on 2025-06-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("employee_count", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("sales_for_year", models.CharField(max_length=100)),
                ("export_experience", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("possible_product", models.TextField()),
                ("alarm", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
