# Generated by Django 5.0.2 on 2025-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("po_admin", "0002_adminmember_custuser_region_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custuser",
            name="alarm",
            field=models.DateField(),
        ),
    ]
