# Generated by Django 5.0.2 on 2025-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("po_admin", "0003_alter_custuser_alarm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custuser",
            name="alarm",
            field=models.DateField(blank=True, null=True),
        ),
    ]
