# Generated by Django 5.0.2 on 2025-06-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("po_admin", "0004_alter_custuser_alarm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custuser",
            name="employee_count",
            field=models.IntegerField(),
        ),
    ]
