# Generated by Django 5.0.2 on 2025-06-27 19:03

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_users(apps, schema_editor):
    User = apps.get_model('diary', 'User')
    
    users_data = [
        {
            'name': '김철수',
            'email': 'kim.chulsu@example.com',
            'password': make_password('password123')
        },
        {
            'name': '이영희',
            'email': 'lee.younghee@example.com',
            'password': make_password('password123')
        },
        {
            'name': '박민수',
            'email': 'park.minsu@example.com',
            'password': make_password('password123')
        },
        {
            'name': '최지원',
            'email': 'choi.jiwon@example.com',
            'password': make_password('password123')
        },
        {
            'name': '정수영',
            'email': 'jung.suyoung@example.com',
            'password': make_password('password123')
        }
    ]
    
    for user_data in users_data:
        User.objects.get_or_create(
            email=user_data['email'],
            defaults={
                'name': user_data['name'],
                'password': user_data['password']
            }
        )


def reverse_create_users(apps, schema_editor):
    User = apps.get_model('diary', 'User')
    
    emails = [
        'kim.chulsu@example.com',
        'lee.younghee@example.com',
        'park.minsu@example.com',
        'choi.jiwon@example.com',
        'jung.suyoung@example.com'
    ]
    
    User.objects.filter(email__in=emails).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_auto_20250627_1902"),
    ]

    operations = [
        migrations.RunPython(create_users, reverse_create_users),
    ]
