# Generated by Django 5.0.2 on 2025-06-27 19:05

from django.db import migrations


def create_base_attributes_and_attributes(apps, schema_editor):
    AttributeType = apps.get_model('diary', 'AttributeType')
    BaseAttribute = apps.get_model('diary', 'BaseAttribute')
    Attribute = apps.get_model('diary', 'Attribute')
    User = apps.get_model('diary', 'User')
    
    # Get AttributeType instances
    dropdown_type = AttributeType.objects.get(name='dropdown')
    datetime_type = AttributeType.objects.get(name='datetime')
    region_type = AttributeType.objects.get(name='region')
    region_detail_type = AttributeType.objects.get(name='region_detail')
    text_type = AttributeType.objects.get(name='text')
    
    # Get User instance (user ID 1)
    try:
        user = User.objects.get(id=1)
    except User.DoesNotExist:
        user = User.objects.first()  # fallback to first user if ID 1 doesn't exist
    
    # Define attributes with their types
    attributes_data = [
        ('대출', text_type),
        ('가능성', text_type),
        ('영업진행', dropdown_type),
        ('F/U 일정', datetime_type),
        ('미팅', datetime_type),
        ('TA', datetime_type),
        ('이메일', text_type),
        ('연락처', text_type),
        ('담당자', text_type),
        ('수수', text_type),
        ('상세지역', region_detail_type),
        ('지역', region_type),
        ('구분', dropdown_type),
        ('매출', text_type),
    ]
    
    # Create BaseAttributes and Attributes
    for attr_name, attr_type in attributes_data:
        # Create BaseAttribute
        base_attr, created = BaseAttribute.objects.get_or_create(
            name=attr_name,
            defaults={'attributeType': attr_type}
        )
        
        # Create Attribute for user
        Attribute.objects.get_or_create(
            name=attr_name,
            user=user,
            defaults={'attributeType': attr_type}
        )


def reverse_create_base_attributes_and_attributes(apps, schema_editor):
    BaseAttribute = apps.get_model('diary', 'BaseAttribute')
    Attribute = apps.get_model('diary', 'Attribute')
    
    attribute_names = [
        '대출', '가능성', '영업진행', 'F/U 일정', '미팅', 'TA',
        '이메일', '연락처', '담당자', '수수', '상세지역', '지역', '구분', '매출'
    ]
    
    BaseAttribute.objects.filter(name__in=attribute_names).delete()
    Attribute.objects.filter(name__in=attribute_names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0004_auto_20250627_1903"),
    ]

    operations = [
        migrations.RunPython(create_base_attributes_and_attributes, reverse_create_base_attributes_and_attributes),
    ]
