# Generated by Django 5.0.2 on 2025-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0005_auto_20250627_1905"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="assential",
            field=models.BooleanField(default=True),
        ),
    ]
