# Generated by Django 5.0.2 on 2025-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0006_attribute_assential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="assential",
            field=models.BooleanField(default=False),
        ),
    ]
