# Generated by Django 5.0.2 on 2025-06-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0007_alter_attribute_assential"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="detail",
            field=models.BooleanField(default=False),
        ),
    ]
