# Generated by Django 5.0.2 on 2025-06-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0008_attribute_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseAttributeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "attributeType",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_attribute_details",
                        to="diary.attributetype",
                    ),
                ),
            ],
        ),
    ]
