# Generated by Django 5.0.2 on 2025-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0009_baseattributedetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.TextField(),
        ),
    ]
