# Generated by Django 5.0.2 on 2025-07-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0010_alter_attributevalue_value"),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='order',
            field=models.IntegerField(default=0, db_index=True),
        ),
    ] 