# Generated by Django 5.0.2 on 2025-07-03 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0011_auto_20250703_1119"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.RenameField(
            model_name="attribute",
            old_name="order",
            new_name="sort_order",
        ),
    ]
