# Generated by Django 5.0.2 on 2025-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0012_alter_attribute_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="view_select",
            field=models.BooleanField(default=False),
        ),
    ]
