# Generated by Django 5.0.2 on 2025-07-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0013_attribute_view_select"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_fields",
                    models.JSONField(default=list, help_text="카드에 표시할 내용 필드들의 리스트"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_field",
                    models.ForeignKey(
                        help_text="카드 생성 기준 날짜 필드",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_date_settings",
                        to="diary.attribute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_settings",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "캘린더 설정",
                "verbose_name_plural": "캘린더 설정",
                "unique_together": {("user",)},
            },
        ),
    ]
