# Generated by Django 5.0.2 on 2025-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0014_calendarsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarsettings",
            name="content_fields",
        ),
        migrations.RemoveField(
            model_name="calendarsettings",
            name="date_field",
        ),
        migrations.AddField(
            model_name="calendarsettings",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
