# Generated by Django 5.0.2 on 2025-07-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0015_remove_calendarsettings_content_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="cascade",
            field=models.BooleanField(default=False),
        ),
    ]
