# Generated by Django 5.0.2 on 2025-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0016_attribute_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="copy_from",
            field=models.IntegerField(default=None),
        ),
    ]
