# Generated by Django 5.0.2 on 2025-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0017_attributevalue_copy_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevalue",
            name="copy_from",
            field=models.IntegerField(default=0),
        ),
    ]
