# Generated by Django 5.0.2 on 2025-07-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0018_alter_attributevalue_copy_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="row",
            name="copied_row_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="row",
            name="original_row",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copied_rows_rel",
                to="diary.row",
            ),
        ),
    ]
