# Generated by Django 5.0.2 on 2025-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0019_row_copied_row_ids_row_original_row"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="row",
            name="original_row",
        ),
        migrations.AddField(
            model_name="row",
            name="original_row_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
