# Generated by Django 5.0.2 on 2025-07-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0020_remove_row_original_row_row_original_row_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="view_select",
            field=models.JSONField(default=dict),
        ),
    ]
