# Generated by Django 5.0.2 on 2025-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0021_update_attribute_view_select"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="view_select",
            field=models.BooleanField(default=False),
        ),
    ]
