# Generated by Django 5.0.2 on 2025-07-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0022_alter_attribute_view_select"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dropdownattribute",
            options={"ordering": ["attribute", "order", "id"]},
        ),
        migrations.AddField(
            model_name="dropdownattribute",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
