# Generated by Django 5.0.2 on 2025-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0023_alter_dropdownattribute_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="view_select",
            field=models.JSONField(default=dict),
        ),
    ]
