# Generated by Django 5.0.2 on 2025-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0024_alter_attribute_view_select"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="width",
            field=models.IntegerField(default=150),
        ),
    ]
