# Generated by Django 5.0.2 on 2025-07-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0025_attribute_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
