# Generated by Django 5.0.2 on 2025-07-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0026_alter_attribute_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="width",
            field=models.IntegerField(default=180),
        ),
    ]
