# Generated by Django 5.0.2 on 2025-07-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0027_alter_attribute_width"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_settings",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "칸반보드 설정",
                "verbose_name_plural": "칸반보드 설정",
                "unique_together": {("user",)},
            },
        ),
    ]
