# Generated by Django 5.0.2 on 2025-07-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0028_kanbansettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="manager_name",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
