# Generated by Django 5.0.2 on 2025-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0029_user_company_name_user_manager_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
