# Generated by Django 5.0.2 on 2025-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0030_alter_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "contact",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("content", models.TextField(blank=True, default="", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "문의",
                "verbose_name_plural": "문의",
                "ordering": ["-created_at"],
            },
        ),
    ]
