# Generated by Django 5.0.2 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0032_alarm_useralarm"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
