# Generated by Django 5.0.2 on 2025-07-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0033_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="content",
            field=models.JSONField(default=dict),
        ),
    ]
