# Generated by Django 5.0.2 on 2025-07-24 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0036_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
