# Generated by Django 5.0.2 on 2025-07-24 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0037_delete_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="board",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="author",
        ),
        migrations.DeleteModel(
            name="Board",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
