# Generated by Django 5.0.2 on 2025-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0038_remove_comment_board_remove_comment_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("verification_code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "이메일 인증",
                "verbose_name_plural": "이메일 인증",
            },
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="attribute",
            index=models.Index(
                fields=["user", "sort_order"], name="diary_attri_user_id_12ff54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attribute",
            index=models.Index(
                fields=["user", "name"], name="diary_attri_user_id_c8f361_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attribute",
            index=models.Index(
                fields=["user", "detail"], name="diary_attri_user_id_28af38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attribute",
            index=models.Index(
                fields=["attributeType", "name"], name="diary_attri_attribu_131e5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attributevalue",
            index=models.Index(
                fields=["row", "attribute"], name="diary_attri_row_id_d85c6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attributevalue",
            index=models.Index(
                fields=["attribute", "row"], name="diary_attri_attribu_d8ea11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(fields=["order"], name="diary_diary_order_158451_idx"),
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(
                fields=["created_at"], name="diary_diary_created_7ecdb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(
                fields=["category", "status"], name="diary_diary_categor_220785_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dropdownattribute",
            index=models.Index(
                fields=["attribute", "order"], name="diary_dropd_attribu_38e80c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dropdownattribute",
            index=models.Index(
                fields=["attribute", "id"], name="diary_dropd_attribu_1848e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="row",
            index=models.Index(
                fields=["user", "order"], name="diary_row_user_id_27d7c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="row",
            index=models.Index(
                fields=["user", "created_at"], name="diary_row_user_id_90dc65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["email", "verification_code"],
                name="diary_email_email_821f0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["email", "is_verified"], name="diary_email_email_9ae9a0_idx"
            ),
        ),
    ]
