# Generated by Django 5.0.2 on 2025-08-01 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0029_update_alarm_charset"),
        ("diary", "0039_emailverification_alter_diaryentry_created_at_and_more"),
    ]

    operations = []
