# Generated by Django 5.0.2 on 2025-08-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0040_merge_20250801_1037"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alarm",
            options={"verbose_name": "공지사항", "verbose_name_plural": "공지사항"},
        ),
        migrations.AddField(
            model_name="attribute",
            name="detail_sort_order",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="title",
            field=models.CharField(db_collation="utf8mb4_unicode_ci", max_length=100),
        ),
        migrations.AlterModelTable(
            name="alarm",
            table="diary_alarm",
        ),
    ]
