# Generated by Django 5.0.2 on 2025-08-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0041_alter_alarm_options_attribute_detail_sort_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(db_collation="utf8mb4_unicode_ci", max_length=200),
                ),
                ("content", models.TextField(db_collation="utf8mb4_unicode_ci")),
                ("files", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시판",
                "verbose_name_plural": "게시판",
                "db_table": "diary_board",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(db_collation="utf8mb4_unicode_ci", max_length=255),
                ),
                ("saved_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=100)),
                ("s3_key", models.CharField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_files",
                        to="diary.board",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시판 첨부파일",
                "verbose_name_plural": "게시판 첨부파일",
                "db_table": "diary_board_file",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["author", "-created_at"], name="diary_board_author__8b0590_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["-created_at"], name="diary_board_created_76f885_idx"
            ),
        ),
    ]
