# Generated by Django 5.0.2 on 2025-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0042_board_boardfile_board_diary_board_author__8b0590_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="use_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
