# Generated by Django 5.0.2 on 2025-08-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0043_user_use_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary_diary_count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ip"], name="diary_diary_ip_c62d5a_idx"),
                    models.Index(
                        fields=["created_at"], name="diary_diary_created_fa2fa7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Diary_main_count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ip"], name="diary_diary_ip_872caa_idx"),
                    models.Index(
                        fields=["created_at"], name="diary_diary_created_13419a_idx"
                    ),
                ],
            },
        ),
    ]
