# Generated by Django 5.0.2 on 2025-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0044_diary_diary_count_diary_main_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyViewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=1)),
                (
                    "page_type",
                    models.CharField(
                        choices=[("main", "메인 페이지"), ("diary", "다이어리 페이지")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip", "date"], name="diary_daily_ip_2ad890_idx"
                    ),
                    models.Index(fields=["date"], name="diary_daily_date_d19ed7_idx"),
                    models.Index(
                        fields=["page_type"], name="diary_daily_page_ty_57ad10_idx"
                    ),
                ],
                "unique_together": {("ip", "date", "page_type")},
            },
        ),
    ]
