# Generated by Django 5.0.2 on 2025-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0045_dailyviewrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="diary_class_created_d3bb94_idx"
                    )
                ],
            },
        ),
    ]
