# Generated by Django 5.0.2 on 2025-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0046_classform"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="diary_count_created_d23aec_idx"
                    )
                ],
            },
        ),
    ]
