# Generated by Django 5.0.2 on 2025-08-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0047_countuser"),
    ]

    operations = [
        # 테이블이 삭제되었으므로 다시 생성
        migrations.CreateModel(
            name="NomalBoardCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(db_collation="utf8mb4_unicode_ci", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_categories",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시판 카테고리",
                "verbose_name_plural": "게시판 카테고리",
                "db_table": "diary_nomal_board_category",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="nomalboardcategory",
            index=models.Index(
                fields=["user", "category_name"], name="diary_board_user_id_575068_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomalboardcategory",
            index=models.Index(fields=["user"], name="diary_board_user_id_56dda2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="nomalboardcategory",
            unique_together={("user", "category_name")},
        ),
        # category 컬럼은 이미 DB에 존재하므로, 상태만 추가한다
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="board",
                    name="category",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="diary.nomalboardcategory",
                    ),
                ),
            ],
        ),
        # MySQL에서 빈 문자열을 NULL로 변경한 후 BIGINT로 변환
        migrations.RunSQL(
            sql=(
                "UPDATE `diary_board` SET `category_id` = NULL WHERE `category_id` = ''; "
                "ALTER TABLE `diary_board` MODIFY COLUMN `category_id` BIGINT NULL"
            ),
            reverse_sql=(
                "ALTER TABLE `diary_board` MODIFY COLUMN `category_id` TEXT NULL"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["category", "-created_at"],
                name="diary_board_categor_3f9ecb_idx",
            ),
        ),
    ]
