# Generated by Django 5.0.2 on 2025-08-19 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0048_nomalboardcategory_board_category_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="nomalboardcategory",
            table="diary_nomal_board_category",
        ),
    ]
