# Generated by Django 5.0.2 on 2025-08-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0049_alter_nomalboardcategory_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alarm",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
            },
        ),
        migrations.AlterModelTable(
            name="nomalboardcategory",
            table="nomal_diary_board_category",
        ),
        migrations.CreateModel(
            name="AlarmCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(db_collation="utf8mb4_unicode_ci", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_categories",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항 카테고리",
                "verbose_name_plural": "공지사항 카테고리",
                "db_table": "diary_alarm_category",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="alarm",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alarms",
                to="diary.alarmcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(
                fields=["category", "-created_at"],
                name="diary_alarm_categor_55be92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(
                fields=["-created_at"], name="diary_alarm_created_76391e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmcategory",
            index=models.Index(
                fields=["user", "category_name"], name="diary_alarm_user_id_262f08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmcategory",
            index=models.Index(fields=["user"], name="diary_alarm_user_id_79521e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="alarmcategory",
            unique_together={("user", "category_name")},
        ),
    ]
