# Generated by Django 5.0.2 on 2025-08-19 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0050_alter_alarm_options_alter_nomalboardcategory_table_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="nomalboardcategory",
            new_name="nomal_diary_user_id_3ad9f6_idx",
            old_name="diary_board_user_id_575068_idx",
        ),
        migrations.RenameIndex(
            model_name="nomalboardcategory",
            new_name="nomal_diary_user_id_a9a5a2_idx",
            old_name="diary_board_user_id_56dda2_idx",
        ),
        migrations.AlterModelTable(
            name="nomalboardcategory",
            table="nomal_diary_board_category",
        ),
    ]
