# Generated by Django 5.0.2 on 2025-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "diary",
            "0051_rename_diary_board_user_id_575068_idx_nomal_diary_user_id_3ad9f6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activate",
            field=models.BooleanField(default=True),
        ),
    ]
