# Generated by Django 5.0.2 on 2025-08-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0052_user_activate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountUserIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_user_ips",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ip"], name="diary_count_ip_e657c9_idx"),
                    models.Index(
                        fields=["created_at"], name="diary_count_created_f9dbea_idx"
                    ),
                ],
            },
        ),
    ]
