# Generated by Django 5.0.2 on 2025-09-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0053_countuserip"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_name", models.CharField(max_length=255)),
                ("price", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="diary_payam_created_b25777_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TossPaymentBillingKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_key", models.CharField(max_length=255)),
                ("billing_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_type", models.CharField(max_length=255)),
                ("last_billing_date", models.DateTimeField(blank=True, null=True)),
                ("rebill_date", models.DateField(blank=True, null=True)),
                ("billing_status", models.CharField(max_length=255)),
                ("billing_activate", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toss_user",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "billing_key"],
                        name="diary_tossp_user_id_6f5c38_idx",
                    ),
                    models.Index(
                        fields=["user"], name="diary_tossp_user_id_bf95e0_idx"
                    ),
                ],
            },
        ),
    ]
