# Generated by Django 5.0.2 on 2025-09-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0054_payamount_tosspaymentbillingkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_history_user",
                        to="diary.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="diary_payhi_user_id_15684a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="diary_payhi_created_92e583_idx"
                    ),
                ],
            },
        ),
    ]
