# Generated by Django 5.0.2 on 2025-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0055_payhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="tosspaymentbillingkey",
            name="billing_success_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
