# Generated by Django 5.0.2 on 2025-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0057_payhistory_billing_success_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tosspaymentbillingkey",
            name="rebill_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
