# Generated by Django 5.0.2 on 2025-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0058_alter_tosspaymentbillingkey_rebill_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pc_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
