# Generated by Django 5.0.2 on 2025-10-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0059_user_pc_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIClassContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("hero", "메인 헤로 섹션"),
                            ("stats", "통계 섹션"),
                            ("barriers", "3가지 벽 섹션"),
                            ("benefits", "혜택 섹션"),
                            ("ai_tools", "AI 툴 섹션"),
                            ("instructor", "강사 소개 섹션"),
                            ("class_info", "강의 정보 섹션"),
                            ("cta", "CTA 섹션"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="섹션 제목", max_length=200, null=True
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(blank=True, help_text="섹션 부제목", null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="섹션 설명", null=True),
                ),
                ("content", models.TextField(blank=True, help_text="추가 내용", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 클래스 페이지 내용",
                "verbose_name_plural": "AI 클래스 페이지 내용",
                "indexes": [
                    models.Index(
                        fields=["section"], name="diary_aicla_section_fcdbc7_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIClassTextElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="템플릿에서 사용할 고유 키", max_length=100, unique=True
                    ),
                ),
                ("text", models.TextField(help_text="표시될 텍스트 내용")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="이 텍스트 요소에 대한 설명",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 클래스 텍스트 요소",
                "verbose_name_plural": "AI 클래스 텍스트 요소",
                "indexes": [
                    models.Index(fields=["key"], name="diary_aicla_key_a8f76a_idx")
                ],
            },
        ),
    ]
