# Generated by Django 5.0.2 on 2025-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0060_aiclasscontent_aiclasstextelement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFormTextElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="고유 키 (예: form.title, form.date)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(help_text="실제 표시될 텍스트")),
                (
                    "description",
                    models.CharField(blank=True, help_text="관리자용 설명", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI 클래스 폼 텍스트",
                "verbose_name_plural": "AI 클래스 폼 텍스트",
                "db_table": "diary_classform_text_element",
                "ordering": ["key"],
            },
        ),
    ]
