# Generated by Django 5.0.2 on 2025-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0061_classformtextelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="classform",
            name="desired_date",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
