# Generated by Django 5.0.2 on 2025-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("big_category", models.CharField(max_length=100)),
                ("small_category", models.CharField(max_length=100)),
            ],
        ),
    ]
