# Generated by Django 5.0.2 on 2025-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_count", models.IntegerField(default=0)),
                ("search_count", models.IntegerField(default=0)),
                ("search_result_count", models.IntegerField(default=0)),
                ("board_count", models.IntegerField(default=0)),
                ("board_detail_count", models.IntegerField(default=0)),
                ("inquiry_count", models.IntegerField(default=0)),
            ],
        ),
    ]
