# Generated by Django 5.0.2 on 2025-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="count",
            old_name="board_count",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="count",
            name="board_detail_count",
        ),
        migrations.RemoveField(
            model_name="count",
            name="inquiry_count",
        ),
        migrations.RemoveField(
            model_name="count",
            name="main_count",
        ),
        migrations.RemoveField(
            model_name="count",
            name="search_count",
        ),
        migrations.RemoveField(
            model_name="count",
            name="search_result_count",
        ),
        migrations.AddField(
            model_name="count",
            name="count_type",
            field=models.CharField(
                choices=[
                    ("main", "메인페이지"),
                    ("search", "검색창"),
                    ("search_result", "검색결과"),
                    ("board", "공고 리스트"),
                    ("board_detail", "공고 상세"),
                    ("inquiry", "문의페이지"),
                ],
                default=0,
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
