# Generated by Django 5.0.2 on 2025-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_ipaddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Count_by_date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_type", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
