# Generated by Django 5.0.2 on 2025-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_count_by_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="count_by_date",
            name="count_type",
            field=models.CharField(max_length=50),
        ),
    ]
