# Generated by Django 5.0.2 on 2025-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_count_by_date_count_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipaddress",
            name="count",
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="count_type",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
