# Generated by Django 5.0.2 on 2025-06-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_ipaddress_count_ipaddress_count_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BizTop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pblanc_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("update_date", models.CharField(max_length=100)),
            ],
        ),
    ]
