# Generated by Django 5.0.2 on 2025-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "manager_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("use_date", models.DateTimeField(blank=True, null=True)),
                ("activate", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("verification_code", models.CharField(max_length=6)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "이메일 인증",
                "verbose_name_plural": "이메일 인증",
                "indexes": [
                    models.Index(
                        fields=["email", "verification_code"],
                        name="salesmate_e_email_76d581_idx",
                    ),
                    models.Index(
                        fields=["email", "is_verified"],
                        name="salesmate_e_email_e3495c_idx",
                    ),
                ],
            },
        ),
    ]
