# Generated by Django 5.0.2 on 2025-04-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counsel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("region", models.CharField(max_length=50)),
                ("industry", models.CharField(max_length=50)),
                ("start_date", models.CharField(max_length=10)),
                ("sales_2024", models.CharField(blank=True, max_length=30, null=True)),
                ("sales_2025", models.CharField(blank=True, max_length=30, null=True)),
                ("inquiry_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
