# Generated by Django 5.0.2 on 2025-05-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counsel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="counsel",
            name="consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="counsel",
            name="consent2",
            field=models.BooleanField(default=False),
        ),
    ]
