# Generated by Django 5.0.2 on 2025-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counsel", "0003_rename_sales_2024_counsel_sales_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("inquiry", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consent", models.BooleanField(default=False)),
                ("consent2", models.BooleanField(default=False)),
            ],
        ),
    ]
