# Generated by Django 5.0.2 on 2025-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BizInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pblanc_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("reception_start", models.DateField(max_length=200)),
                ("reception_end", models.DateField(max_length=200)),
                ("registered_at", models.DateField(blank=True, null=True)),
                ("institution_name", models.CharField(max_length=200)),
                ("enroll_method", models.CharField(max_length=200)),
                ("target", models.CharField(max_length=200)),
                ("field", models.CharField(max_length=200)),
                ("hashtag", models.CharField(max_length=200)),
                ("print_file_name", models.CharField(max_length=200)),
                ("print_file_path", models.CharField(max_length=200)),
                ("company_hall_path", models.CharField(max_length=200)),
                ("support_field", models.CharField(max_length=200)),
                ("application_form_path", models.CharField(max_length=200)),
                ("application_form_name", models.CharField(max_length=200)),
            ],
        ),
    ]
