# Generated by Django 5.0.2 on 2025-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizinfo',
            name='iframe_src',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
