# Generated by Django 5.0.2 on 2025-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_bizinfo_iframe_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="application_form_path",
            field=models.CharField(max_length=500),
        ),
    ]
