# Generated by Django 5.0.2 on 2025-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_alter_bizinfo_enroll_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="iframe_src",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
