# Generated by Django 5.0.2 on 2025-05-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_alter_bizinfo_iframe_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="hashtag",
            field=models.CharField(max_length=500),
        ),
    ]
