# Generated by Django 5.0.2 on 2025-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0006_alter_bizinfo_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="bizinfo",
            name="employee_count",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bizinfo",
            name="revenue",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
