# Generated by Django 5.0.2 on 2025-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0007_bizinfo_employee_count_bizinfo_revenue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="revenue",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
