# Generated by Django 5.0.2 on 2025-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0008_alter_bizinfo_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="bizinfo",
            name="noti_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
