# Generated by Django 5.0.2 on 2025-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0009_bizinfo_noti_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="bizinfo",
            name="business_period",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
