# Generated by Django 5.0.2 on 2025-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0010_bizinfo_business_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="bizinfo",
            name="export_performance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bizinfo",
            name="possible_industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bizinfo",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
