# Generated by Django 5.0.2 on 2025-05-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0011_bizinfo_export_performance_bizinfo_possible_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="possible_industry",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
