# Generated by Django 5.0.2 on 2025-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0012_alter_bizinfo_possible_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="possible_industry",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
