# Generated by Django 5.0.2 on 2025-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0013_alter_bizinfo_possible_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="region",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
