# Generated by Django 5.0.2 on 2025-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0014_alter_bizinfo_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bizinfo",
            name="application_form_name",
            field=models.CharField(max_length=400),
        ),
    ]
